### ISSUE TITLE
Build obstacle on debian stable

### ISSUE THREAD

**Issue by cratuki** [andrewrk/libsoundio#60]
Here, I will describe a build problem that happens when I try to compile libsoundio under a debian stable environment.

= Background

Here's my system:
memlab$ uname -a
Linux memlab 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
memlab$ apt-cache show clang | grep Version
Version: 1:3.5-25
memlab$ 

I downloaded libsoundio-1.1.0.tar.gz and unpacked it.

= Cmake steps

$ cd libsoundio-1.1.0; mkdir build; cd build; cmake ..
-- The C compiler identification is Clang 3.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
Configuring libsoundio version 1.1.0
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found JACK: /usr/lib/x86_64-linux-gnu/libjack.so  
-- Found PULSEAUDIO: /usr/lib/x86_64-linux-gnu/libpulse.so  
-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.0.28") 
-- Could NOT find COREAUDIO (missing:  COREAUDIO_LIBRARY COREAUDIO_INCLUDE_DIR) 
-- Could NOT find WASAPI (missing:  WASAPI_INCLUDE_DIR) 

Installation Summary
--------------------
* Install Directory            : /usr/local
* Build Type                   : Debug
* Build static libs            : ON
* Build examples               : ON
* Build tests                  : ON

System Dependencies
-------------------
* threads                      : OK
* JACK       (optional)        : OK
* PulseAudio (optional)        : OK
* ALSA       (optional)        : OK
* CoreAudio  (optional)        : not found
* WASAPI     (optional)        : not found

-- Configuring done
-- Generating done
-- Build files have been written to: /home/cturner/saga/20160304.memlab.cturner.ad.libsoundio/000.poc/libsoundio-1.1.0/build
$ 

= Make

memlab$ make
Scanning dependencies of target libsoundio_shared
[  2%] Building C object CMakeFiles/libsoundio_shared.dir/src/soundio.c.o
/home/cturner/saga/20160304.memlab.cturner.ad.libsoundio/000.poc/libsoundio-1.1.0/src/soundio.c:180:47: error: illegal initializer type 'atomic_flag' (aka
      '_Atomic(struct (anonymous struct at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include/stdatomic.h:232:17))')
static struct SoundIoAtomicFlag rtprio_seen = SOUNDIO_ATOMIC_FLAG_INIT;
                                              ^
/home/cturner/saga/20160304.memlab.cturner.ad.libsoundio/000.poc/libsoundio-1.1.0/src/atomics.h:68:35: note: expanded from macro 'SOUNDIO_ATOMIC_FLAG_INIT'
#define SOUNDIO_ATOMIC_FLAG_INIT {ATOMIC_FLAG_INIT}
                                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include/stdatomic.h:241:26: note: expanded from macro 'ATOMIC_FLAG_INIT'
#define ATOMIC_FLAG_INIT        { 0 }
                                ^
1 error generated.
CMakeFiles/libsoundio_shared.dir/build.make:54: recipe for target 'CMakeFiles/libsoundio_shared.dir/src/soundio.c.o' failed
make[2]: *** [CMakeFiles/libsoundio_shared.dir/src/soundio.c.o] Error 1
CMakeFiles/Makefile2:192: recipe for target 'CMakeFiles/libsoundio_shared.dir/all' failed
make[1]: *** [CMakeFiles/libsoundio_shared.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
memlab$ 

= Notes

I'd be happy to be a part of the solution for this, but I'm not particularly skilled with compiler tool-chains and would benefit from guidance.

Shortly after building this, I also tried to build zig language. Zig failed because debian stable is running an older version of LLVM than is required by zig.

This makes me think - an approach to fixing this might be for me to create a compiler toolchain in isolation. For example, a barebones linux under qemu, and then install tools from source towards being able to build this. I could put some towards this, but - again - would appreciate guidance on what to focus on.

**Comment by tresf** [comment]
Just an outsider lurking... 

Some work on this is happening over at https://github.com/andrewrk/libsoundio/pull/50.  You may want to clone the fork and post your progress.   :+1:

**Comment by cratuki** [comment]
Thanks tresf. I've cloned the git repo, and read through #49 and #50.

I'm running origin/master. When I attempt to build, I get the same behaviour as above. I suspect I need to do something to get to the fork you refer to - please can you spell out how I get my local mirror of the codebase onto the fork?

**Comment by tresf** [comment]
@cratuki,

My mistake for not reading the bug report fully.  At the time of posting my hint, it had already been merged (from January), so the changes discussed are and have been live in master branch, which is default.  To answer your question, yes there's a way to checkout a specific branch and I'd be happy to explain that to you if you'd like, but in this case, it won't help.

> I'm not particularly skilled with compiler tool-chains and would benefit from guidance.

I'm not particularly skilled with C/C++ but can help with some of the toolchain stuff :+1:  although this one is probably best left for the author. :)

**Comment by andrewrk** [comment]
I'm sorry I didn't see this earlier. I believe this was caused by #50. Fix coming shortly.

**Comment by ideoforms** [comment]
I'm afraid this now causes compile errors due to `-Werror=missing-braces`, on LLVM version 7.3.0 (clang-703.0.29) on OS X 10.11, and gcc 4.9 on Ubuntu 14.04.3 (gcc 4.9.3-8ubuntu2~14.04)

```
Scanning dependencies of target libsoundio_shared
[  2%] Building C object CMakeFiles/libsoundio_shared.dir/src/soundio.c.o
/Users/daniel/libsoundio/src/soundio.c:180:47: error: suggest braces around initialization of subobject
      [-Werror,-Wmissing-braces]
static struct SoundIoAtomicFlag rtprio_seen = SOUNDIO_ATOMIC_FLAG_INIT;
                                              ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/daniel/libsoundio/src/atomics.h:68:34: note: expanded from macro 'SOUNDIO_ATOMIC_FLAG_INIT'
#define SOUNDIO_ATOMIC_FLAG_INIT ATOMIC_FLAG_INIT
                                 ^~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include/stdatomic.h:165:28: note: 
      expanded from macro 'ATOMIC_FLAG_INIT'
#define ATOMIC_FLAG_INIT { 0 }
                           ^
1 error generated.
```

I resolved by by restoring the `{ ATOMIC_FLAG_INIT }` brackets - but this would obviously revert this fix. Haven't been able to get the bottom of what the difference is between the systems. Perhaps an issue with older `clang`?

**Comment by andrewrk** [comment]
What if you remove the define and directly use ATOMIC_FLAG_INIT everywhere? Does that solve the compile error for you?

**Comment by andrewrk** [comment]
Hmm never mind that last comment. I'm going to simply disable this silly warning.

**Comment by andrewrk** [comment]
@ideoforms could you try with this latest commit?

**Comment by ideoforms** [comment]
Works great. Thanks!
